; Arquivo de configuracao do projeto Next2350
; Para mais detalhes, consulte a documentacao oficial do PlatformIO.

[env:next2350_board]
platform = raspberrypi
board = rpipico2  ; Substitua pelo ID exato da placa se ja existir no registro
framework = arduino ; Ou 'pico-sdk' se voce for usar o SDK puro
monitor_speed = 115200

; Configuracoes de upload
upload_protocol = picotool

; Bibliotecas necessarias para o seu projeto
lib_deps =
    adafruit/Adafruit ILI9341 @ ^6.1.0
    adafruit/Adafruit GFX Library @ ^1.11.9